### ISSUE TITLE
Load Typescript scraper

### ISSUE THREAD

**Issue by Ashraf-Ali-aa** [luka-dev/secret-agent-task-server#1]
I was wondering is lt possible to post TS file to the task server rather than just js file

**Comment by luka-dev** [comment]
Hello, reason to use simple JS it's to avoid additional dependencies on the production server. 
Because compiling on the fly can request not only 'typescript' module and all imported libs in scraper script.
But you can do it on your own side before sanding it to the server: https://github.com/Microsoft/TypeScript-wiki/blob/main/Using-the-Compiler-API.md#a-simple-transform-function
